CONFIG_ZMK_SPLIT=y

# Правая половина — peripheral (не имеет центрального контроллера)
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
CONFIG_ZMK_USB=n


CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
CONFIG_NICE_VIEW_GEM_MODIFIERS=y
# Включаем виджет индикаторов модификаторов в nice_view_gem
# (на дисплее отображаются ⌘ ⌥ ⌃ ⇧ при нажатии Ctrl/Alt/Gui/Shift)
